/**
 * Generates `dist/<slug>/_headers` — the Cloudflare Pages security headers.
 *
 * The Content-Security-Policy is **measured, never assumed**. Every hash and
 * every allowed origin below comes from reading the built HTML this run
 * produced, because a policy written from what we believe the pages contain is
 * a policy that is wrong the first time a client's config differs — and wrong
 * in the worst direction, either breaking the site or silently permitting more
 * than it needs to.
 *
 * Why generated rather than a static `public/_headers`:
 *
 *   - Two of the four inline scripts have per-client bytes. `Customizer.astro`
 *     uses `define:vars` to embed that client's preset matrix, and
 *     `DesignLayout.astro`'s no-flash resolver embeds `offeredIds(design)`. A
 *     hand-written hash would be correct for one client and wrong for the rest.
 *   - A third depends on a feature flag: `ServiceWorker.astro` emits a
 *     *register* script or an *unregister* script depending on
 *     `features.offline`.
 *   - Turnstile's script is emitted only when `forms.turnstileSiteKey` is set,
 *     so its origin belongs in the policy of the builds that use it and no
 *     others.
 *
 * The two judgement calls, recorded rather than buried:
 *
 *   script-src is hash-only, and never gains 'unsafe-inline'. That is the half
 *   of CSP that actually stops cross-site scripting, and it is achievable here
 *   because every inline script is ours and finite. `check-headers.mjs`
 *   asserts this on every build so it cannot drift in quietly.
 *
 *   style-src carries 'unsafe-inline', because it must. There are inline style
 *   *attributes* across the design components (`style="margin: 0;"`,
 *   `style={--d-reveal-delay: …}`), and CSP hashes do not cover attributes.
 *   CSP3's 'unsafe-hashes' would, at the cost of one hash per attribute value,
 *   regenerated whenever any of that copy changes, with weaker support — worse
 *   on every axis. The cost of the allowance is nil here because there is no
 *   way to inject markup in the first place: see docs/injection-surface.md,
 *   which proves there is no HTML sink at all, and check-injection.mjs, which
 *   keeps it that way.
 *
 * Usage:
 *   node scripts/gen-headers.mjs              # the client SITE_CLIENT selected
 *   node scripts/gen-headers.mjs <slug>       # one named client
 *   node scripts/gen-headers.mjs --all        # every client present in dist/
 */
import { existsSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { DENIED_FEATURES, buildPolicy, measureClient, walkHtml } from './lib/csp.mjs';

const distRoot = join(fileURLToPath(new URL('.', import.meta.url)), '..', 'dist');

function generate(slug) {
  const distDir = join(distRoot, slug);
  if (!existsSync(distDir)) {
    console.error(`✗ ${slug}: no dist/${slug}. Run a build first.`);
    return false;
  }
  if (walkHtml(distDir).length === 0) {
    console.error(`✗ ${slug}: no HTML in dist/${slug}.`);
    return false;
  }

  const { merged } = measureClient(distDir);

  // A page with an executable inline script that produced no hash would mean
  // the policy is about to break that page. Fail rather than ship it.
  if (merged.unhashable.length > 0) {
    console.error(`\n✗ ${slug}: inline script(s) could not be hashed:\n`);
    for (const u of merged.unhashable) console.error(`    ${u}`);
    return false;
  }

  const policy = buildPolicy(merged);
  const body = [
    '# Generated by scripts/gen-headers.mjs — do not edit by hand.',
    '#',
    '# The CSP is measured from this build\'s own HTML: one hash per inline',
    '# script, and only the origins the pages actually reference. Rebuilding',
    '# regenerates it; scripts/check-headers.mjs fails the build if this file',
    '# and the HTML ever disagree.',
    '',
    '/*',
    `  Content-Security-Policy: ${policy}`,
    '  X-Content-Type-Options: nosniff',
    '  Referrer-Policy: strict-origin-when-cross-origin',
    // Redundant against frame-ancestors for any current browser, and one line
    // for the ones that predate it.
    '  X-Frame-Options: DENY',
    `  Permissions-Policy: ${DENIED_FEATURES.map((f) => `${f}=()`).join(', ')}`,
    '',
  ].join('\n');

  writeFileSync(join(distDir, '_headers'), body, 'utf8');

  // Reported off the policy that was actually written, not off the inputs, so
  // the line cannot describe a policy different from the one on disk.
  const frameSrc = /frame-src ([^;]+)/.exec(policy)?.[1] ?? '?';
  console.log(
    `✓ ${slug}: _headers written — ${merged.hashes.size} script hash(es), ` +
      `${merged.scriptHosts.size} external script host(s), ` +
      `${merged.connectHosts.size} connect host(s), frame-src ${frameSrc}.`,
  );
  return true;
}

const requested = process.argv[2];
let slugs;
try {
  if (requested === '--all') {
    slugs = readdirSync(distRoot).filter((d) => statSync(join(distRoot, d)).isDirectory());
  } else {
    slugs = [requested || process.env.SITE_CLIENT || 'kh-machine-works'];
  }
} catch {
  console.error('No dist/ directory. Run a build first.');
  process.exit(1);
}

const results = slugs.map(generate);
process.exit(results.every(Boolean) ? 0 : 1);
