/**
 * The copy engine's command line.
 *
 *   node dist/cli.js check            # generate everything, publish nothing
 *   node dist/cli.js report           # write REPORT.md
 *   node dist/cli.js emit [slug|--all]  # write the markdown content files
 *
 * `check` is the one that matters in CI. Generation is where the fabrication
 * guard runs, so simply generating every client — and throwing away the
 * result — is a full assertion that no client's copy makes an unsourced
 * claim. It needs no fixtures and it cannot drift from what the build emits,
 * because it is the same code path.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { checkBergenList } from './bergen.js';
import { generate, type Generated } from './generate/index.js';
import { PROSPECT_SLUGS, checkProspects, prospectFor } from './prospects/index.js';

const here = dirname(fileURLToPath(import.meta.url));
const packageRoot = join(here, '..');
const templateRoot = join(packageRoot, '..', 'template');

function generateAll(): Map<string, Generated> {
  checkBergenList();
  checkProspects();
  const out = new Map<string, Generated>();
  for (const slug of PROSPECT_SLUGS) out.set(slug, generate(prospectFor(slug)));
  return out;
}

function check(): void {
  const all = generateAll();
  for (const [slug, g] of all) {
    const bits = [
      `${g.faq.length} FAQ`,
      `${g.serviceAreas.length} town sections`,
      `${g.serviceConfig.length} services`,
      `${g.markers.length} markers`,
    ];
    console.log(`✓ ${slug}: ${bits.join(', ')}`);
    for (const w of g.seoWarnings) {
      console.warn(
        `  ! ${slug} seo.${w.field} is ${w.length} chars against a ${w.budget} budget — ` +
          `it will be truncated in a result listing:\n    ${w.text}`,
      );
    }
    for (const u of g.unmappedServices) {
      console.warn(`  ! ${slug} ${u.field}: no niche template matched; minimal description used.`);
    }
  }
  console.log(`\n${all.size} clients generated, no unsourced claims.`);
}

/** Markdown needs its own escaping decision; frontmatter strings get quoted. */
function yamlString(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

function emit(only: string | undefined): void {
  const slugs = only === undefined || only === '--all' ? PROSPECT_SLUGS : [only];
  for (const slug of slugs) {
    const g = generate(prospectFor(slug));

    const aboutDir = join(templateRoot, 'src', 'content', 'about', slug);
    mkdirSync(aboutDir, { recursive: true });
    writeFileSync(
      join(aboutDir, 'about.md'),
      `---\ntitle: ${yamlString(g.about.headline.replace(/\.$/, ''))}\n---\n\n` +
        `${g.about.paragraphs.join('\n\n')}\n`,
      'utf8',
    );

    const servicesDir = join(templateRoot, 'src', 'content', 'services', slug);
    mkdirSync(servicesDir, { recursive: true });
    for (const s of g.serviceMarkdown) {
      const frontmatter = [
        '---',
        `title: ${yamlString(s.title)}`,
        `summary: ${yamlString(s.summary)}`,
        'highlights:',
        ...s.highlights.map((h) => `  - ${yamlString(h)}`),
        '---',
      ].join('\n');
      writeFileSync(
        join(servicesDir, `${s.slug}.md`),
        `${frontmatter}\n\n${s.paragraphs.join('\n\n')}\n`,
        'utf8',
      );
    }
    console.log(`✓ ${slug}: about.md + ${g.serviceMarkdown.length} service files`);
  }
}

function report(): void {
  const all = generateAll();
  const lines: string[] = [];

  lines.push('# Copy engine — what is still open');
  lines.push('');
  lines.push(
    'Generated by `pnpm --filter @site-factory/copy report`. Every entry below is a',
    'question for the business owner, not a task for an engineer. Nothing here blocks a',
    'mockup — markers are what a mockup is for — but every one of them blocks a live',
    'build, because `check-markers.mjs` refuses to publish a marker.',
    '',
  );

  for (const [slug, g] of all) {
    const record = prospectFor(slug);
    lines.push(`## ${record.legalName.value}`);
    lines.push('');
    lines.push(
      `\`${slug}\` · ${record.niche} · ${record.town.value}, ${record.region.value}` +
        (record.county === undefined ? '' : ` · ${record.county.value}`),
    );
    lines.push('');
    lines.push(
      `${g.faq.length} FAQ questions · ${g.droppedQuestions.length} dropped as unanswerable · ` +
        `${g.serviceAreas.length} town sections · ${g.markers.length} markers remaining`,
    );
    lines.push('');

    if (g.markers.length > 0) {
      lines.push('### Markers in the copy — each clears with one answer');
      lines.push('');
      lines.push('| Field | Ask the owner |');
      lines.push('| --- | --- |');
      for (const m of g.markers) lines.push(`| \`${m.field}\` | ${m.question} |`);
      lines.push('');
    }

    if (g.droppedQuestions.length > 0) {
      lines.push('### FAQ questions we could not answer, so did not ask');
      lines.push('');
      lines.push(
        'These are dropped rather than hedged. Answer one and it appears in the FAQ on the',
        'next run.',
        '',
      );
      for (const d of g.droppedQuestions) lines.push(`- **${d.field}** — ${d.question}`);
      lines.push('');
    }

    if (g.unmappedServices.length > 0) {
      lines.push('### Services with no niche template');
      lines.push('');
      for (const u of g.unmappedServices) lines.push(`- **${u.field}** — ${u.question}`);
      lines.push('');
    }

    if (g.toReadBack.length > 0) {
      lines.push('### Facts carried from the earlier mockups — worth reading back');
      lines.push('');
      lines.push(
        'These were not sourced afresh in this run. They came from the approved mockup',
        'configs, which an earlier stream wrote from each shop\'s own material — real',
        'provenance, one hop longer than the rest, and a hop is where a value goes stale.',
        '',
      );
      lines.push('| Field | Value | Where it came from |');
      lines.push('| --- | --- | --- |');
      for (const t of g.toReadBack) {
        const v = t.value.length > 60 ? `${t.value.slice(0, 57)}…` : t.value;
        lines.push(`| \`${t.field}\` | ${v} | ${t.evidence.replace(/^CARRIED:\s*/, '')} |`);
      }
      lines.push('');
    }

    const ours = g.about.voiceNotes.filter((v) => v.attributed !== 'owner');
    if (ours.length > 0) {
      lines.push('### About-section prose that is ours, not theirs');
      lines.push('');
      lines.push(
        'Read these back and ask the owner to correct them into their own words. Accurate',
        'is not the same as theirs, and the About page is the one they judge hardest.',
        '',
      );
      for (const v of ours) lines.push(`- “${v.phrase}”\n  <br>*${v.source}*`);
      lines.push('');
    }

    if (g.seoWarnings.length > 0) {
      lines.push('### SEO strings that overrun a listing');
      lines.push('');
      for (const w of g.seoWarnings) {
        lines.push(`- \`${w.field}\` — ${w.length} chars against a ${w.budget} budget`);
      }
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push('## Totals');
  lines.push('');
  lines.push('| Client | FAQ | Towns | Markers | Dropped Qs | To read back |');
  lines.push('| --- | ---: | ---: | ---: | ---: | ---: |');
  for (const [slug, g] of all) {
    lines.push(
      `| ${slug} | ${g.faq.length} | ${g.serviceAreas.length} | ${g.markers.length} | ` +
        `${g.droppedQuestions.length} | ${g.toReadBack.length} |`,
    );
  }
  lines.push('');

  const path = join(packageRoot, 'REPORT.md');
  writeFileSync(path, `${lines.join('\n')}\n`, 'utf8');
  console.log(`Wrote ${path}`);
}

/** Sanity output for a single client, for eyeballing a change. */
function show(slug: string): void {
  const g = generate(prospectFor(slug));
  console.log(JSON.stringify(g, null, 2));
}

const [command, arg] = process.argv.slice(2);
try {
  switch (command) {
    case 'check':
    case undefined:
      check();
      break;
    case 'report':
      report();
      break;
    case 'emit':
      emit(arg);
      break;
    case 'show':
      if (arg === undefined) throw new Error('show needs a client slug');
      show(arg);
      break;
    default:
      console.error(`Unknown command "${command}". Try: check | report | emit | show <slug>`);
      process.exit(2);
  }
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
}
