import { createHash } from 'node:crypto';
import { existsSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';

import type { APIRoute } from 'astro';

import { clientSlug, site } from '../../site.config';

/**
 * `/sw.js` — the service worker, generated at build time.
 *
 * Why an endpoint rather than a static file in `public/`: the precache list
 * has to be the *real* one. `features.gallery` decides whether `/gallery`
 * exists at all, and the image set is whatever is actually in `public/`. A
 * hand-maintained list in a static file would be wrong the first time a client
 * config differed from the one it was written against — and wrong quietly,
 * because a missing precache entry only shows up when somebody is standing in
 * a workshop with no signal.
 *
 * What it is for: these sites get demoed on a phone inside shops with bad
 * reception. After one visit on any connection, every page must open instantly
 * and completely on no connection at all.
 *
 * Strategy, and the reasoning:
 *   - navigations  network-first with a short timeout. A connected phone always
 *                  gets the current build; a disconnected one falls back to the
 *                  cache instead of the browser's error page.
 *   - everything   cache-first. Images, fonts and the hashed `/_astro/` island
 *     else         bundle never change under a given URL, so serving them from
 *                  the cache is both correct and fast. Anything not precached
 *                  (the island bundle, whose hash is not knowable here) is
 *                  cached the first time it is fetched — which is exactly the
 *                  "works after the first visit" contract.
 *   - non-GET      not intercepted at all. A form POST cannot be served from a
 *                  cache, and pretending otherwise would show a visitor a
 *                  success state for a message that never left the phone. The
 *                  form detects the offline case itself and says so.
 */

/**
 * The package root, found by walking up from the working directory.
 *
 * Not `import.meta.url`: this module is bundled into `dist/<slug>/pages/`
 * before it runs, so a path relative to the module resolves inside `dist`.
 * `astro build` always runs with the package root as its working directory —
 * both directly and through `scripts/build-all.mjs`, which sets `cwd`
 * explicitly — so walking up for `astro.config.mjs` finds the real root from
 * either entry point.
 */
function packageRoot(): string {
  let dir = resolve(process.cwd());
  for (;;) {
    if (existsSync(join(dir, 'astro.config.mjs'))) return dir;
    const parent = dirname(dir);
    if (parent === dir) {
      throw new Error(
        `sw.js: could not find the template package root above ${process.cwd()}. ` +
          `Run the build from packages/template.`,
      );
    }
    dir = parent;
  }
}

const publicDir = join(packageRoot(), 'public');

/** Every file under `public/`, as the root-absolute URL it is served at. */
function publicAssets(dir: string = publicDir): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      out.push(...publicAssets(full));
      continue;
    }
    out.push(`/${relative(publicDir, full).split(sep).join('/')}`);
  }
  return out.sort();
}

/**
 * Trailing slashes: the build emits `services/index.html`, and the config sets
 * `trailingSlash: 'ignore'`, so `/services` and `/services/` are the same page.
 * The precache stores the slashed form and the fetch handler normalises
 * incoming navigations to match, so both spellings hit.
 */
function routes(): string[] {
  return [
    '/',
    '/services/',
    '/about/',
    '/contact/',
    ...(site.features.gallery ? ['/gallery/'] : []),
    // Cached so an unknown URL offline gets this site's own 404 page rather
    // than the browser's "you are offline" screen.
    '/404.html',
  ];
}

export const GET: APIRoute = () => {
  const assets = publicAssets();
  const precache = [...routes(), ...assets];

  /**
   * The cache name changes whenever the config or the asset set changes, and
   * old caches are deleted on activate. It does NOT change when only page copy
   * in a content collection changes — which is survivable because HTML is
   * network-first, so a connected phone still gets the new bytes; only a
   * genuinely offline phone can show yesterday's page, and showing yesterday's
   * page is the entire point of being offline-capable.
   */
  const version = createHash('sha256')
    .update(JSON.stringify({ site, precache }))
    .digest('hex')
    .slice(0, 12);

  const body = `/* Generated by src/pages/sw.js.ts — do not edit in dist/. */
const CACHE = 'site-factory:${clientSlug}:${version}';
const PRECACHE = ${JSON.stringify(precache, null, 2)};
const NOT_FOUND = '/404.html';
/* Long enough for a slow-but-real connection, short enough that a phone with
   one flickering bar does not sit on a white screen. */
const NETWORK_TIMEOUT_MS = 3500;

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      /* One at a time rather than cache.addAll(): addAll is all-or-nothing, so
         a single 404 would leave the site with no offline support at all and
         no clue why. A miss here costs one uncached asset. */
      await Promise.all(
        PRECACHE.map(async (url) => {
          try {
            const res = await fetch(url, { cache: 'reload' });
            if (res.ok) await cache.put(url, res);
          } catch (err) {
            /* Ignored on purpose: see above. */
          }
        }),
      );
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names
          .filter((name) => name.startsWith('site-factory:') && name !== CACHE)
          .map((name) => caches.delete(name)),
      );
      await self.clients.claim();
    })(),
  );
});

/** '/services', '/services/' and '/services/index.html' are one page. */
function variants(pathname) {
  const withSlash = pathname.endsWith('/') ? pathname : pathname + '/';
  const withoutSlash = pathname.length > 1 ? pathname.replace(/\\/+$/, '') : '/';
  return [pathname, withSlash, withoutSlash, withSlash + 'index.html'];
}

async function fromCache(request) {
  const cache = await caches.open(CACHE);
  const direct = await cache.match(request, { ignoreSearch: true });
  if (direct) return direct;

  const url = new URL(request.url);
  for (const candidate of variants(url.pathname)) {
    const hit = await cache.match(candidate, { ignoreSearch: true });
    if (hit) return hit;
  }
  return undefined;
}

function timedFetch(request) {
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error('timeout')), NETWORK_TIMEOUT_MS);
    fetch(request).then(
      (res) => {
        clearTimeout(timer);
        resolve(res);
      },
      (err) => {
        clearTimeout(timer);
        reject(err);
      },
    );
  });
}

async function networkFirst(request) {
  try {
    const res = await timedFetch(request);
    if (res && res.ok) {
      const cache = await caches.open(CACHE);
      cache.put(request, res.clone());
    }
    return res;
  } catch (err) {
    const cached = await fromCache(request);
    if (cached) return cached;
    const fallback = await caches.open(CACHE).then((c) => c.match(NOT_FOUND));
    if (fallback) return fallback;
    throw err;
  }
}

async function cacheFirst(request) {
  const cached = await fromCache(request);
  if (cached) return cached;
  const res = await fetch(request);
  if (res && res.ok) {
    const cache = await caches.open(CACHE);
    cache.put(request, res.clone());
  }
  return res;
}

self.addEventListener('fetch', (event) => {
  const request = event.request;

  /* Form POSTs and anything else with a body go straight to the network. */
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  /* Third-party requests (Turnstile, if a site key is configured) are none of
     this worker's business. */
  if (url.origin !== self.location.origin) return;

  event.respondWith(request.mode === 'navigate' ? networkFirst(request) : cacheFirst(request));
});
`;

  return new Response(body, {
    headers: {
      'Content-Type': 'text/javascript; charset=utf-8',
      /* The worker script itself must never be served stale, or a phone can be
         pinned to an old cache indefinitely. */
      'Cache-Control': 'no-cache',
    },
  });
};
